# ekf.yaml  (한 파일 안에 3개 섹션)

# --- EKF #1: odom EKF (wheel odom + IMU) ---
ekf_odom:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    two_d_mode: true

    # frames
    base_link_frame: base_link
    odom_frame: odom
    map_frame: map
    world_frame: odom          
    publish_tf: true           # This node publish TF odom->base_link

    # wheel odom (GZ diffdrive /odom)
    odom0: /odom
    odom0_differential: false
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]

    # IMU
    imu0: /imu/data
    imu0_differential: false
    imu0_queue_size: 50
    imu0_nodelay: true
    imu0_remove_gravitational_acceleration: true
    imu0_config:  [false, false, false,
                   true,  true,  true,
                   false, false, false,
                   true,  true,  true,
                   false, false, false]

    transform_time_offset: 0.0
    sensor_timeout: 0.1
    print_diagnostics: true


# --- NavSat Transform (GPS -> Odometry) ---
navsat_transform:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0

    # inputs
    imu_topic: /imu/data
    odom_topic: /odometry/filtered        # ekf_odom output
    gps_topic: /gps/fix

    # outputs
    publish_filtered_gps: true            # /gps/filtered 
    #  /odometry/gps

    zero_altitude: true
    use_odometry_yaw: true
    magnetic_declination_radians: 0.0
    wait_for_datum: false


# --- EKF #2: map EKF (odom EKF + GPS ) ---
ekf_map:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true

    # frames
    base_link_frame: base_link
    odom_frame: odom
    map_frame: map
    world_frame: map           # map EKF는 world=map
    publish_tf: true           # This node publish TF map -> odom

    # Input 1: ekf_odom output
    odom0: /odometry/filtered
    odom0_differential: false
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]

    # Input 2: navsat_transform output
    odom1: /odometry/gps
    odom1_differential: false
    odom1_queue_size: 10
    odom1_nodelay: true
    odom1_config: [true,  true,  false,
                   false, false, true,     
                   false, false, false,
                   false, false, false,
                   false, false, false]

    transform_time_offset: 0.0
    sensor_timeout: 0.2
    print_diagnostics: true
