<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Camera Stand -->
<xacro:macro name="camera_stand" params="link_name parent xyz rpy length:=0.8 radius:=0.02">
    <link name="${link_name}">
        <inertial>
            <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
            <mass value="0.5"/>
            <inertia 
                ixx="1e-3" ixy="0" ixz="0" 
                iyy="1e-3" iyz="0" 
                izz="1e-3"/>
        </inertial>

        <visual>
            <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>

            <geometry>
                <cylinder length="${length}" radius="${radius}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>

            <geometry>
                <cylinder length="${length}" radius="${radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="${link_name}_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${link_name}"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>
</xacro:macro>



<!-- RGB-D Camera -->
<!-- Camera + depth_camera-->
<xacro:macro name="rgbd_camera"
             params="link_name parent joint_name xyz rpy prefix
                     width:=640 height:=480 hfov:=1.0471976
                     near:=0.05 far:=15.0 rate:=30">

    <link name="${link_name}">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.2"/>
            <inertia 
                ixx="5e-4" ixy="0" ixz="0" 
                iyy="5e-4" iyz="0" 
                izz="5e-4"/>
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>
                <box size="0.05 0.06 0.04"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>

            <geometry>
                <box size="0.05 0.06 0.04"/>
            </geometry>
        </collision>
    </link>

    <joint name="${joint_name}" type="fixed">
        <parent link="${parent}"/>
        <child link="${link_name}"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>




    <!-- Gazebo RGB Camera + Depth Camera-->
    <gazebo reference="${link_name}">
        <sensor name="${prefix}_rgb" type="camera">
            <always_on>1</always_on>
            <visualize>true</visualize>
            <update_rate>${rate}</update_rate>
            <topic>${prefix}/rgb/image</topic>
            <ignition_frame_id>${prefix}_optical_frame</ignition_frame_id>

            <camera>
                <horizontal_fov>${hfov}</horizontal_fov>

                <image>
                    <width>${width}</width>
                    <height>${height}</height>
                    <format>R8G8B8</format>
                </image>

                <clip>
                    <near>${near}</near>
                    <far>${far}</far>
                </clip>
            </camera>
        </sensor>
    </gazebo>



    <!-- Depth Camera-->
    <gazebo reference="${link_name}">
        <sensor name="${prefix}_depth" type="depth_camera">
            <always_on>1</always_on>
            <visualize>true</visualize>
            <update_rate>${rate}</update_rate>
            <topic>${prefix}/depth/image</topic>
            <ignition_frame_id>${prefix}_optical_frame</ignition_frame_id>

            <camera>
                <horizontal_fov>${hfov}</horizontal_fov>

                <image>
                    <width>${width}</width>
                    <height>${height}</height>
                    <format>R_FLOAT32</format>
                </image>

                <clip>
                    <near>${near}</near>
                    <far>${far}</far>
                </clip>
            </camera>

            <depth_camera>
                <point_cloud>true</point_cloud>
                <min_range>0.05</min_range>
                <max_range>15.0</max_range>
                <resolution>0.001</resolution>
            </depth_camera>
        </sensor>
    </gazebo>



    <link name="${prefix}_optical_frame"/>
    <joint name="${prefix}_optical_joint" type="fixed">
        <parent link="${link_name}"/>
        <child link="${prefix}_optical_frame"/>
        <origin xyz="0 0 0" rpy="-1.5707963 0 -1.5707963"/>
    </joint>

</xacro:macro>
</robot>